name: anita-workshop

channels:
  # Conda forge - gives us lots of community-built Python packages, see https://conda-forge.org/ for details
  - conda-forge  

dependencies:
  - python >= 3.6
  - numpy
  - scipy
  - astropy
  - matplotlib
  - jupyterlab
  - ipykernel
  - pip
  - pip:
    - line_profiler
    - memory_profilier